FROM golang:1.21.4 AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o main .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .

# EXPOSE 8080

CMD ["./main"]

